# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: Cache@2
    condition: ne(variables['System.PullRequest.PullRequestId'], '')
    displayName: Cache LLVM
    inputs:
      key: 'llvm_13_0_0_0 | llvmUpdateKey'
      restoreKeys: llvmUpdateKey
      path: $(Agent.TempDirectory)\llvm
      cacheHitVar: LLVM_CACHE_RESTORED

  - task: PowerShell@2
    displayName: Downloading LLVM
    condition: and(ne(variables['System.PullRequest.PullRequestId'], ''), ne(variables.LLVM_CACHE_RESTORED, 'true'))
    inputs:
        targetType: 'inline'
        script: |
          $url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/LLVM-13.0.0-win64.exe"
          $output = "$(Agent.TempDirectory)\LLVM-13.0.0-win64.exe"
          (New-Object Net.WebClient).DownloadFile($url, $output)
        errorActionPreference: 'stop'
        failOnStderr: 'true'

  - task: ExtractFiles@1
    displayName: Install LLVM
    condition: and(ne(variables['System.PullRequest.PullRequestId'], ''), ne(variables.LLVM_CACHE_RESTORED, 'true'))
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)\LLVM-13.0.0-win64.exe' 
      destinationFolder: '$(Agent.TempDirectory)\llvm'
  
  - script: echo "##vso[task.prependpath]$(Agent.TempDirectory)\llvm\bin"
    displayName: Add LLVM to PATH
    condition: ne(variables['System.PullRequest.PullRequestId'], '')
