# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: repoDirectory
    type: string
    default: $(Build.SourcesDirectory)

steps:
  - script: |
      echo Checking PATH variable...
      echo %PATH%
      echo.

    displayName: Check path
  - script: |
      dir
    displayName: dummy step

  - script: |
      ninja --version
    displayName: Ninja Version Check
