# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  - task: DotNetCoreCLI@2  
    condition: ne(variables['system.pullrequest.isfork'], true)
    displayName: Install NBGV tool
    inputs:
      command: custom
      custom: tool
      arguments: install --tool-path . nbgv

  - script: nbgv cloud -a -c
    condition: ne(variables['system.pullrequest.isfork'], true)
    displayName: Set build number

  # Currently Azure pipelines won't let PRs from forks setting the build ID
  # so we need to come up with a version number to use for the build
  - task: PowerShell@2
    condition: eq(variables['system.pullrequest.isfork'], true)
    displayName: Set temporary build number
    inputs:
        targetType: 'inline'
        script: |
            Write-Host "$("##vso[task.setvariable variable=NBGV_Version]")0.0.0"
            Write-Host "$("##vso[task.setvariable variable=NBGV_VersionMajor]")0"
            Write-Host "$("##vso[task.setvariable variable=NBGV_VersionMinor]")0"
            Write-Host "$("##vso[task.setvariable variable=NBGV_BuildNumber]")0"
            Write-Host "$("##vso[task.setvariable variable=NBGV_VersionHeight]")$env:System_PullRequest_PullRequestNumber"
            Write-Host "$("##vso[task.setvariable variable=NBGV_AssemblyInformationalVersion]")00000000000"
            Write-Host "$("##vso[task.setvariable variable=NBGV_NuGetPackageVersion]")0.0.0-alpha.$env:System_PullRequest_PullRequestNumber"

  - task: PowerShell@2
    displayName: Get target build counter
    inputs:
        targetType: 'inline'
        script: |
            $counter = $env:REVISION
            $version = ([int]$counter).ToString()

            if($env:Build_SourceBranch.StartsWith('release-') -or 
               $env:Build_SourceBranch.StartsWith('main'))
            {
                Write-Host "$("##vso[task.setvariable variable=TARGET_BUILD_COUNTER]")$env:NBGV_BuildNumber"
            }
            else
            {
                Write-Host "$("##vso[task.setvariable variable=TARGET_BUILD_COUNTER]")$version"
            }

