# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  - name: buildDirectory
    type: string
    default: '$(Build.SourcesDirectory)\build'

steps:
  - task: CopyFiles@2
    condition: succeeded()
    displayName: Collecting deployable artifacts
    inputs:
      sourceFolder: ${{ parameters.buildDirectory }}
      Contents: |
        *.bin
        *.hex
        *.dfu
        *.csv
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(TargetPublishName)'
      flattenFolders: true
      ignoreMakeDirErrors: true
