# Copyright (c) 2018 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

parameters:
  buildDirectory: '$(Build.SourcesDirectory)\build'

steps:
  - task: CopyFiles@1
    inputs:
      sourceFolder: ${{ parameters.buildDirectory }}
      Contents: |
        *.bin
        *.hex
        *.s19
        *.dfu
      TargetFolder: '$(Build.ArtifactStagingDirectory)\$(BoardName)'
      flattenFolders: true
    condition: and( succeeded(), ne(variables['Build.Reason'], 'PullRequest') )
    displayName: Collecting deployable artifacts

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\$(BoardName)'
      ArtifactName: $(BoardName)
      ArtifactType: Container
    condition: and( succeeded(), ne(variables['Build.Reason'], 'PullRequest') )
    displayName: Publish deployables artifacts
