# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  repoDirectory: '$(Build.SourcesDirectory)'

steps:

  - task: PowerShell@2
    displayName: Composer CMakeUserPresets
    inputs:
      workingDirectory:  ${{ parameters.repoDirectory }}
      targetType: 'inline'
      script: |
        $file = "CMakeUserPresets.json"

        Rename-Item -Path "CMakeUserPresets.TEMPLATE.json" -NewName $file
        
        $filecontent = Get-Content($file)
        attrib $file -r
        $filecontent -replace  'Debug', 'MinSizeRel' | Out-File $file -Encoding UTF8

        [regex]$pattern='user-local-tools'
        $pattern.replace([IO.File]::ReadAllText($file), 'user-local-tools-dummy', 1) | Out-File $file -Encoding UTF8

        $filecontent = Get-Content($file)
        $filecontent -replace  'user-local-tools-cloud', 'user-local-tools' | Out-File $file -Encoding UTF8
