# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

name: Build Dev Container for TI

env:
  GCR_IMAGE: ghcr.io/nanoframework/dev-container-ti
  GCR_FILE: .devcontainer/sources/Dockerfile.TI

on:
  push:
    branches:
      - develop
    paths:
      - '**Dockerfile.TI'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get container version
      run: |
        $dockerfileContent = Get-Content(".devcontainer/Dockerfile.TI")
        $dockerfileContent -match '(?<=\:)(?:[v]\d+.\d+)'
        $containerVersion = $Matches[0].ToString()
        echo "GCR_VERSION=$containerVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_BUILD_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        file: ${{ env.GCR_FILE }}
        push: true # Will only build if this is not here
        tags: |
          ${{ env.GCR_IMAGE }}:${{ env.GCR_VERSION }}
          ${{ env.GCR_IMAGE }}:latest
